pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Install Java and Run Hello World') {
      agent {
        docker { image 'openjdk:11-jdk' }
      }
      steps {
        sh 'java -version'
        sh 'echo "Hello, World!"'
      }
    }
  }
}
